project:
  type: website
  output-dir: docs

website:
  title: "Hello Quarto and Targets"
  description: "Demonstrating ecological concepts and statistical models using simulation"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/aammd
      - icon: twitter
        href: https://twitter.com/polesasunder
format:
  html:
    theme: minty
    css: styles.css

editor: visual

